name: flutter_examen1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.4.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/tareas.json
    - asset/image/welcome.jpg
    - asset/image/welcome.webp
    - asset/image/CIE2024.jpg
    - asset/image/premios.jpg
    - asset/image/donacion.jpeg
    - asset/document/